### ISSUE TITLE
Kann den Service nicht starten

### ISSUE THREAD

**Issue by ransome1** [retani/uberspace-meteor#1]
Hi,

ich folge Deiner Anleitung bis zum Start des Services auf dem Uberspace Server: `uberspace-setup-service reaction node ~/reaction/bundle/main.js`

Dieser Befehl schmeißt leider diese Meldung:
```
2017-05-26 23:51:54.890016500 /home/xyz/reaction/bundle/programs/server/mini-files.js:82
2017-05-26 23:51:54.890554500 const unicodeNormalizePath = (path) => {
2017-05-26 23:51:54.890588500                                      ^
2017-05-26 23:51:54.894932500 SyntaxError: Unexpected token >
2017-05-26 23:51:54.894933500     at Module._compile (module.js:439:25)
2017-05-26 23:51:54.894934500     at Object.Module._extensions..js (module.js:474:10)
2017-05-26 23:51:54.894934500     at Module.load (module.js:356:32)
2017-05-26 23:51:54.894935500     at Function.Module._load (module.js:312:12)
2017-05-26 23:51:54.894936500     at Module.require (module.js:364:17)
2017-05-26 23:51:54.894936500     at require (module.js:380:17)
2017-05-26 23:51:54.894936500     at Object.<anonymous> (/home/robster/XYZ/bundle/programs/server/boot.js:9:13)
2017-05-26 23:51:54.894964500     at Module._compile (module.js:456:26)
2017-05-26 23:51:54.894964500     at Object.Module._extensions..js (module.js:474:10)
2017-05-26 23:51:54.894965500     at Module.load (module.js:356:32)
```

Wo könnte ich hier anfangen das Problem zu lösen?

Gruß
Robin

**Comment by retani** [comment]
Hi Robin,

Die Fehlermeldung sieht nach einem Versionsproblem von Javascript/ECMAScript/ES bzw. node aus. 

`(path) => {...` ist eine Art, Funktionen zu deklarieren, die soweit ich weiß erst seit ES6 existiert. Frühere Versionen müssen es also als Syntax-Fehler verstehen. Siehe beispielsweise: [https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Functions/Pfeilfunktionen]()

Ab node 6 werden die Pfeilfunktionen 100% korrekt unterstützt, siehe [http://node.green/#ES2015-functions-arrow-functions]()

Überprüfe doch mal mit `node -v` deine node-version.

**Comment by ransome1** [comment]
Hallo Retani,

danke für die Rückmeldung. Installiert habe ich lokal dieselbe Version wie die auf dem Uberspace: 0.10.43.

Ich bin mittlerweile soweit, dass "bin/deploy-to-uberspace" damit beginnt das Build zu bauen.

Kurz nachdem aber die Remote Verbindung aufgebaut wird, schmeißt die Shell diese Fehler:
```
Continuing remotely:
Enter passphrase for key '/Users/XYZ/.ssh/id_rsa': 
Unpacking...
Installing node modules...
tar (child): app.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
/bin/bash: line 6: cd: /home/XYZ/tmp/build/bundle/programs/server/: No such file or directory
npm WARN deprecated This version of npm lacks support for important features,
npm WARN deprecated such as scoped packages, offered by the primary npm
npm WARN deprecated registry. Consider upgrading to at least npm@2, if not the
npm WARN deprecated latest stable version. To upgrade to npm@2, run:
npm WARN deprecated 
npm WARN deprecated   npm -g install npm@latest-2
npm WARN deprecated 
npm WARN deprecated To upgrade to the latest stable version, run:
npm WARN deprecated 
npm WARN deprecated   npm -g install npm@latest
npm WARN deprecated 
npm WARN deprecated (Depending on how Node.js was installed on your system, you
npm WARN deprecated may need to prefix the preceding commands with `sudo`, or if
npm WARN deprecated on Windows, run them from an Administrator prompt.)
npm WARN deprecated 
npm WARN deprecated If you're running the version of npm bundled with
npm WARN deprecated Node.js 0.10 LTS, be aware that the next version of 0.10 LTS
npm WARN deprecated will be bundled with a version of npm@2, which has some small
npm WARN deprecated backwards-incompatible changes made to `npm run-script` and
npm WARN deprecated semver behavior.
npm ERR! install Couldn't read dependencies
npm ERR! package.json ENOENT, open '/home/XYZ/package.json'
npm ERR! package.json This is most likely not a problem with npm itself.
npm ERR! package.json npm can't find a package.json file in your current directory.

npm ERR! System Linux 2.6.32-642.6.2.el6.x86_64
npm ERR! command "/package/host/localhost/nodejs-0.10.43/bin/node" "/usr/local/bin/npm" "install"
npm ERR! cwd /home/XYZ/tmp/build
npm ERR! node -v v0.10.43
npm ERR! npm -v 1.4.29
npm ERR! path /home/XYZ/package.json
npm ERR! code ENOPACKAGEJSON
npm ERR! errno 34
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/XYZ/tmp/build/npm-debug.log
npm ERR! not ok code 0
Stopping server...
Replacing live files...
Starting server...
rm: cannot remove `/home/XYZ/reaction/*': No such file or directory
mv: cannot stat `build/bundle': No such file or directory
Cleaning up...
```

Das Build wurde durch "meteor build" in meinem App Verzeichnis lokal gebaut. Die Node Versionen waren dabei dieselben.

Ursache ist ja vielleicht die nicht gefundene app.tar.gz. Habe ich an irgendeiner Stelle vielleicht den falschen Pfad zum tar gesetzt? 

Gruß

**Comment by ransome1** [comment]
Mal so zum allgemeinen Verständnis, weil ich aus der Anleitung nicht genau erlesen kann, was wo gemacht wird.; Die von Dir beschriebenen Schritte in Setup passieren auf dem Uberspace, korrekt? 

Und die Schritte in Deploy passieren auf meinem lokalen Rechner, von dem aus ich auf Uberspace deployen möchte, oder?

Denn der ganz oben beschriebene Fehler beim Aufruf von "uberspace-setup-service reaction node ~/reaction/bundle/main.js" passiert nämlich auf dem Uberspace, wenn ich versuche den Service zu registrieren. Wenn ich dort ein Versionsproblem habe, dann habe ich ein grundsätzliches Problem, da Uberspace die Version sicherlich nicht erneuern wird. Aber dann müssten auch alle anderen Node.js Admins dieses Problem haben. Oder sehe ich das falsch?

Gruß
bob

**Comment by retani** [comment]
Setup auf Uberspace, Deploy auf lokalem Rechner – korrekt!

Ja, ich denke auch, dass dann alle dieses Problem haben müssten. Hier steht auch, dass Meteor 1.4.x mindestens Node 4.6.2 braucht [https://guide.meteor.com/deployment.html#custom-deployment]()

Hier steht allerdings, dass Uberspace auch verschiedene Node-Versionen bereitstellt! [https://wiki.uberspace.de/development:nodejs#versionen]()

Abgesehen davon fällt mir noch auf, dass `/home/XYZ/...` bei dir angepasst werden muss. 'XYZ' musst du durch deinen Account-Name ersetzen. Den Pfad kannst du auch folgendermaßen sehen:

`$ echo ~`

**Comment by ransome1** [comment]
Ich werde mich mal darum kümmern, eine neuere Version bereitgestellt zu bekommen.

Das XYZ ist nur Teil der Anonymisierung ;))

**Comment by ransome1** [comment]
Node läuft jetzt auf 6.10.3, wie auch auf meiner lokalen Maschine.

Wenn ich den Service starte beschwert sich uberspace allerdings immer noch darüber, dass das Modul 'fibers' nicht gefunden werden kann:
```
2017-05-27 22:10:09.921979500 Error: Cannot find module 'fibers'
2017-05-27 22:10:09.921980500     at Function.Module._resolveFilename (module.js:469:15)
2017-05-27 22:10:09.921980500     at Function.Module._load (module.js:417:25)
2017-05-27 22:10:09.921981500     at Module.require (module.js:497:17)
2017-05-27 22:10:09.921982500     at require (internal/module.js:20:19)
2017-05-27 22:10:09.921982500     at Object.<anonymous> (/home/XYZ/reaction/bundle/programs/server/boot.js:1:75)
2017-05-27 22:10:09.922053500     at Module._compile (module.js:570:32)
2017-05-27 22:10:09.922054500     at Object.Module._extensions..js (module.js:579:10)
2017-05-27 22:10:09.922055500     at Module.load (module.js:487:32)
2017-05-27 22:10:09.922055500     at tryModuleLoad (module.js:446:12)
2017-05-27 22:10:09.922056500     at Function.Module._load (module.js:438:3)
2017-05-27 22:10:10.940253500 module.js:471
2017-05-27 22:10:10.940254500     throw err;
2017-05-27 22:10:10.940255500     ^
```

fibers ist allerdings ein meteor Modul, das ich ja nicht auf uberspace installieren kann.

Im Ordner bundle liegt das, was mir das Ausführen von "meteor build" im App-Ordner lokal ausgespuckt hat. Ist das korrekt?

**Comment by ransome1** [comment]
ich bin ein Stück weiter. Nachdem ich das Bundle auf Uberspace hatte, musste ich noch "npm install" in /bundle/programs/server" ausführen. Vermutlich, um irgendwas zu installieren, das aus de Bundle kommt ;) Ich blick nicht durch.

Das fehlende Modul fibers scheint jetzt aber vorhanden zu sein.

Es folgt der nächste Fehler:
```
/home/XYZ/reaction/bundle/programs/server/node_modules/fibers/future.js:280
						throw(ex);
						^

Error: Must pass options.rootUrl or set ROOT_URL in the server environment
    at Object.Meteor.absoluteUrl (packages/meteor.js:1268:11)
    at Object.WebAppInternals.generateBoilerplate (packages/webapp/webapp_server.js:560:20)
    at Object.WebAppInternals.setInlineScriptsAllowed (packages/webapp/webapp_server.js:847:19)
    at setWebAppInlineScripts (packages/browser-policy-content.js:171:21)
    at Object.setPolicy (packages/browser-policy-content.js:206:5)
    at setDefaultPolicy (packages/browser-policy-content.js:161:25)
    at meteorInstall.node_modules.meteor.browser-policy-content.browser-policy-content.js (packages/browser-policy-content.js:330:1)
    at fileEvaluate (packages/modules-runtime.js:197:9)
    at require (packages/modules-runtime.js:120:16)
    at packages/browser-policy-content.js:337:15
```

Daraufhin habe ich auf de uberspace versucht diese Env zu setzen. Einmal so:
`set ROOT_URL = 'https://...'` Der 'echo $ROOT_URL' spuckt danach auch den korrekten Output.

Auch das hinzufügen von `ROOT_URL = 'https://...'` oder `export ROOT_URL = 'https://...'` in die main.js des Bundles bringt keine Besserung.

Die Fehlermeldung bleibt aber bestehen. Kannst Du mir sagen, auf welche andere Weise ich bei Uberspace Env setzen kann, damit ich den Fehler behoben bekomme?

**Comment by retani** [comment]
Der Schritt mit `npm install` ist übrigens auch im Deploy-script ( [https://github.com/retani/uberspace-meteor/blob/master/deploy/meteor-app/bin/deploy-to-uberspace](bin/deploy-to-uberspace), Zeilen 39-41). Das soll also serverseitig jedes mal durchgeführt werden, wenn du eine neue Version deiner App deployst.

Die Umgebungsvariable setzt du in der aktuellen shell mit 

`export ROOT_URL = 'https://...'`

Damit sie dauerhaft erhalten bleibt, solltest du das Gleiche (`export ROOT_URL...`) zusätzlich zu deiner `~/.bash_profile` hinzufügen. Einfach in einer neuen Zeile am Ende der Datei.

Wünsche viel Erfolg

**Comment by ransome1** [comment]
Das mit den Env hat geklappt. Auch das Building und der Upload waren erfolgreich. Dazu musste ich allerdings erst dem Ordner tmp auf Uberspace die nötigen Rechte geben. Andernfalls hat das Script ohne Hinweis abgebrochen.

Laut Shell sind jetzt viele Module durch das Deploy Script installiert worden. Zwischendurch gab es zwei kleine Fehler, die aber vielleicht nicht weiter schlimm sind:
```
node-pre-gyp ERR! Tried to download(404): https://github.com/kelektiv/node.bcrypt.js/releases/download/v1.0.2/bcrypt_lib-v1.0.2-node-v11-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for bcrypt@1.0.2 and node@0.10.43 (node-v11 ABI) (falling back to source compile with node-gyp) 
```

Geendet hat das Script so:
```
Stopping server...
 will be bundled with a version of npm@2, which has some small
npm WARN deprecated backwards-incompatible changes made to `npm run-script` and
npm WARN deprecated semver behavior.
Replacing live files...
rm: cannot remove `/home/XYZ/reaction/*': No such file or directory
Starting server...
Cleaning up...
```

Es hat also etwas mit dem Aufräumen nicht geklappt, nun gut, nicht so schlimm vermute ich :) Aber woran erkenne ich jetzt, ob die App erfolgreich deployt wurde? Ich App Ordner (reaction) liegt nichts, im HTML Ordner ebenfalls nicht und der Aufruf meiner Root-Url spuckt der Browser eigentlich nur einen 503 Service Temporarily Unavailable aus.

Ich glaube, ich bin fast da :)

**Comment by retani** [comment]
Hast du im Schritt 3 in `~/html/.htaccess` eigentlich den richtigen Port eingetragen? Also der richtige Port ist der, der in Schritt 0 ausgegeben wird.


Ansonsten ist mir das gerade etwas schleierhaft. Die App (genauer App-Bundle) müsste ja schließlich im $uberspace_server_dir liegen. Und $uberspace_server_dir ist bei dir "reaction" - ohne weitere slashes o.ä. - richtig?

Existiert das Verzeichnis und ist schreibbar?

Ich würde als nächstes die vorletzte Zeile von bin/deploy-to-uberspace, `rm -r build`, damit am Schluss nicht gelöscht wird, und dann schauen, ob `~/tmp/build/bundle' existiert.

**Comment by ransome1** [comment]
Hi retani,

ich habe mittlerweile das Script fehlerfrei ausgeführt. Ich glaube, dass ich nur noch ein Proxy Problem habe. Daher ist natürlich deine Frage nach der .htaccess berechtigt. Darin steht:
```
RewriteEngine On
RewriteRule ^(.*)$ http://localhost:64007/$1 [P]
```

Der Befehl `uberspace-list-ports --open` spuckt auch diesen Port aus: `tcp 64007`

In der `/home/XYZ/service/reaction/run` steht:

```
#!/bin/sh
# These environment variables are sometimes needed by the running daemons
export USER=XYZ
export HOME=/home/XYZ
# Include the user-specific profile
source $HOME/.bash_profile
# Now let's go!
exec /package/host/localhost/nodejs-6.10.3/bin/node /home/XYZ/reaction/bundle/main.js 2>&1
export DDP_DEFAULT_CONNECTION_URL=https://XYZ.musca.uberspace.de:64007/
export ROOT_URL='https://XYZ.musca.uberspace.de/'
export PORT=64007
export MONGO_URL='mongodb://XYZ:XYZ@localhost:20988/reaction'
```

Fehlt noch etwas?

**Comment by ransome1** [comment]
das Verzeichnis "reaction" hat chmod 755 und sollte damit beschreibbar sein.

**Comment by retani** [comment]
Hey, ich glaube das `exec...` muss am Ende das Datei stehen, nachdem die Variablen mit `export` gesetzt wurden. 

Hast du mal in den Logs unter `~/services/reaction/log` geschaut?

**Comment by ransome1** [comment]
Danke für den Hinweis, die exec Zeile steht jetzt am Ende.

Der Log spuckt mittlerweile ein schönes Ergebnis:
```
@40000000592d692f2057a7cc Note: you are using a pure-JavaScript implementation of bcrypt.
@40000000592d692f2057c324 While this implementation will work correctly, it is known to be
@40000000592d692f2057c70c approximately three times slower than the native implementation.
@40000000592d692f2057caf4 In order to use the native implementation instead, run
@40000000592d692f2057cedc 
@40000000592d692f2057cedc   meteor npm install --save bcrypt
@40000000592d692f2057d2c4 
@40000000592d692f2057d2c4 in the root directory of your application.
@40000000592d69540bb50c24 12:44:58.191Z  INFO Reaction: Load default data from /private/data/
@40000000592d69543632a434 12:44:58.906Z  INFO Reaction: JobServer started
@40000000592d695502e061ac 12:44:59.047Z  WARN Reaction: Skipped loading settings from reaction.json.
@40000000592d69612b82cd34 12:45:11.728Z  INFO Reaction: Reaction Version: 1.2.0
@40000000592d6961377647c4 12:45:11.928Z  WARN Reaction: OpenExchangeRates API not configured. Not adding fetchRates job
@40000000592d69613835a024 12:45:11.942Z  WARN Reaction: OpenExchangeRates API not configured. Not adding flushRates job
@40000000592d696138dd9824 12:45:11.953Z  WARN Reaction: No cart cleanup schedule
@40000000592d69630c47f19c 12:45:13.205Z  INFO Reaction: Reaction initialization finished.
```

Das bcrypt Problem löse ich lokal und deploye es beim nächsten Mal mit.

Der 503 Fehler ist jetzt auch weg, wurde aber durch einen anderen ersetzt ;)
`An internal server error occurred. Please try again later.`

Das wird wohl mit dem Fehler zusammenhängen, der im error_log des Apaches hängen bleibt:
`[Tue May 30 14:17:19 2017] [error] (111)Connection refused: proxy: HTTP: attempt to connect to 127.0.0.1:64007 (*) failed`

Aber das dürfte doch eigentlich gar nicht passieren, da der Port frei ist und auch in der htaccess eingetragen wurde :(

**Comment by ransome1** [comment]
`netstat -tulpen | grep 64007` sagt:
`tcp        0      0 0.0.0.0:64007               0.0.0.0:*                   LISTEN      988        1246759271 19314/node `

**Comment by ransome1** [comment]
So denn, Uberspace selbst konnte mir bei meiner letzten Meile helfen.

Dein Deployment Script funktioniert einwandfrei und die Applikation läuft und ist ansprechbar.

Allerdings benötigt meine App (reaction) Websockets. Diese schaffen ihren Weg allerdings nicht durch den Proxy, den wir mit der htaccess aufstellen.

Die App ist jetzt mit Eingabe des Ports von außen erreichbar, aber über Port 80 oder 443 wird das nicht passieren können :( Daher kommt Uberspace für mich wohl leider doch nicht in Frage. Sehr schade.

Danke Dir Retani für die Geduld und Hilfe!

Gruß

**Comment by retani** [comment]
Ach, das ist ja ärgerlich. Jetzt wo du es schreibt, kommt mir das Problem bekannt vor. Ich meine, es gibt bei Meteor ein Fallback auf HTTP long polling. Das ist aber natürlich nicht optimal. Schade.
